INDIAN_STOCKS = [
    # NIFTY 50
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries", "index": "NIFTY 50", "sector": "Energy"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services", "index": "NIFTY 50", "sector": "IT"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank", "index": "NIFTY 50", "sector": "Banking"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel", "index": "NIFTY 50", "sector": "Telecom"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank", "index": "NIFTY 50", "sector": "Banking"},
    {"symbol": "INFOSYS.NS", "name": "Infosys", "index": "NIFTY 50", "sector": "IT"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "index": "NIFTY 50", "sector": "Banking"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever", "index": "NIFTY 50", "sector": "FMCG"},
    {"symbol": "ITC.NS", "name": "ITC Limited", "index": "NIFTY 50", "sector": "FMCG"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro", "index": "NIFTY 50", "sector": "Infrastructure"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank", "index": "NIFTY 50", "sector": "Banking"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies", "index": "NIFTY 50", "sector": "IT"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance", "index": "NIFTY 50", "sector": "Finance"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints", "index": "NIFTY 50", "sector": "Consumer"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki", "index": "NIFTY 50", "sector": "Auto"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank", "index": "NIFTY 50", "sector": "Banking"},
    {"symbol": "TITAN.NS", "name": "Titan Company", "index": "NIFTY 50", "sector": "Consumer"},
    {"symbol": "WIPRO.NS", "name": "Wipro", "index": "NIFTY 50", "sector": "IT"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical", "index": "NIFTY 50", "sector": "Pharma"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement", "index": "NIFTY 50", "sector": "Cement"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv", "index": "NIFTY 50", "sector": "Finance"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India", "index": "NIFTY 50", "sector": "FMCG"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corp", "index": "NIFTY 50", "sector": "Energy"},
    {"symbol": "NTPC.NS", "name": "NTPC", "index": "NIFTY 50", "sector": "Power"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation", "index": "NIFTY 50", "sector": "Power"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra", "index": "NIFTY 50", "sector": "Auto"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors", "index": "NIFTY 50", "sector": "Auto"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel", "index": "NIFTY 50", "sector": "Metals"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises", "index": "NIFTY 50", "sector": "Conglomerate"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports & SEZ", "index": "NIFTY 50", "sector": "Infrastructure"},
    {"symbol": "COALINDIA.NS", "name": "Coal India", "index": "NIFTY 50", "sector": "Mining"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories", "index": "NIFTY 50", "sector": "Pharma"},
    {"symbol": "CIPLA.NS", "name": "Cipla", "index": "NIFTY 50", "sector": "Pharma"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra", "index": "NIFTY 50", "sector": "IT"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories", "index": "NIFTY 50", "sector": "Pharma"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries", "index": "NIFTY 50", "sector": "Cement"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries", "index": "NIFTY 50", "sector": "Metals"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel", "index": "NIFTY 50", "sector": "Metals"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank", "index": "NIFTY 50", "sector": "Banking"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals", "index": "NIFTY 50", "sector": "Healthcare"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors", "index": "NIFTY 50", "sector": "Auto"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum", "index": "NIFTY 50", "sector": "Energy"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products", "index": "NIFTY 50", "sector": "FMCG"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp", "index": "NIFTY 50", "sector": "Auto"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance", "index": "NIFTY 50", "sector": "Insurance"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance", "index": "NIFTY 50", "sector": "Insurance"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries", "index": "NIFTY 50", "sector": "FMCG"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto", "index": "NIFTY 50", "sector": "Auto"},
    {"symbol": "UPL.NS", "name": "UPL", "index": "NIFTY 50", "sector": "Agro Chemicals"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance", "index": "NIFTY 50", "sector": "Finance"},

    # NIFTY NEXT 50
    {"symbol": "DMART.NS", "name": "Avenue Supermarts (DMart)", "index": "NIFTY NEXT 50", "sector": "Retail"},
    {"symbol": "SIEMENS.NS", "name": "Siemens India", "index": "NIFTY NEXT 50", "sector": "Engineering"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries", "index": "NIFTY NEXT 50", "sector": "Chemicals"},
    {"symbol": "HAVELLS.NS", "name": "Havells India", "index": "NIFTY NEXT 50", "sector": "Electricals"},
    {"symbol": "DABUR.NS", "name": "Dabur India", "index": "NIFTY NEXT 50", "sector": "FMCG"},
    {"symbol": "MARICO.NS", "name": "Marico", "index": "NIFTY NEXT 50", "sector": "FMCG"},
    {"symbol": "GODREJCP.NS", "name": "Godrej Consumer Products", "index": "NIFTY NEXT 50", "sector": "FMCG"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints", "index": "NIFTY NEXT 50", "sector": "Consumer"},
    {"symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance", "index": "NIFTY NEXT 50", "sector": "Finance"},
    {"symbol": "LUPIN.NS", "name": "Lupin", "index": "NIFTY NEXT 50", "sector": "Pharma"},
    {"symbol": "BIOCON.NS", "name": "Biocon", "index": "NIFTY NEXT 50", "sector": "Pharma"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals", "index": "NIFTY NEXT 50", "sector": "Pharma"},
    {"symbol": "COLPAL.NS", "name": "Colgate-Palmolive India", "index": "NIFTY NEXT 50", "sector": "FMCG"},
    {"symbol": "AMBUJACEM.NS", "name": "Ambuja Cements", "index": "NIFTY NEXT 50", "sector": "Cement"},
    {"symbol": "ACC.NS", "name": "ACC Limited", "index": "NIFTY NEXT 50", "sector": "Cement"},
    {"symbol": "INDIGO.NS", "name": "IndiGo (InterGlobe Aviation)", "index": "NIFTY NEXT 50", "sector": "Aviation"},
    {"symbol": "ZOMATO.NS", "name": "Zomato", "index": "NIFTY NEXT 50", "sector": "Tech"},
    {"symbol": "PAYTM.NS", "name": "Paytm (One97 Communications)", "index": "NIFTY NEXT 50", "sector": "Fintech"},
    {"symbol": "NYKAA.NS", "name": "Nykaa (FSN E-Commerce)", "index": "NIFTY NEXT 50", "sector": "E-Commerce"},
    {"symbol": "POLICYBZR.NS", "name": "PB Fintech (PolicyBazaar)", "index": "NIFTY NEXT 50", "sector": "Fintech"},
    {"symbol": "MPHASIS.NS", "name": "Mphasis", "index": "NIFTY NEXT 50", "sector": "IT"},
    {"symbol": "LTIM.NS", "name": "LTIMindtree", "index": "NIFTY NEXT 50", "sector": "IT"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems", "index": "NIFTY NEXT 50", "sector": "IT"},
    {"symbol": "COFORGE.NS", "name": "Coforge", "index": "NIFTY NEXT 50", "sector": "IT"},
    {"symbol": "OFSS.NS", "name": "Oracle Financial Services", "index": "NIFTY NEXT 50", "sector": "IT"},
    {"symbol": "TATAPOWER.NS", "name": "Tata Power", "index": "NIFTY NEXT 50", "sector": "Power"},
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy", "index": "NIFTY NEXT 50", "sector": "Renewable Energy"},
    {"symbol": "ADANITRANS.NS", "name": "Adani Transmission", "index": "NIFTY NEXT 50", "sector": "Power"},
    {"symbol": "ADANIPOWER.NS", "name": "Adani Power", "index": "NIFTY NEXT 50", "sector": "Power"},
    {"symbol": "INDUSTOWER.NS", "name": "Indus Towers", "index": "NIFTY NEXT 50", "sector": "Telecom"},
    {"symbol": "VEDL.NS", "name": "Vedanta", "index": "NIFTY NEXT 50", "sector": "Metals"},
    {"symbol": "SAIL.NS", "name": "Steel Authority of India", "index": "NIFTY NEXT 50", "sector": "Metals"},
    {"symbol": "NMDC.NS", "name": "NMDC", "index": "NIFTY NEXT 50", "sector": "Mining"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda", "index": "NIFTY NEXT 50", "sector": "Banking"},
    {"symbol": "PNB.NS", "name": "Punjab National Bank", "index": "NIFTY NEXT 50", "sector": "Banking"},
    {"symbol": "CANBK.NS", "name": "Canara Bank", "index": "NIFTY NEXT 50", "sector": "Banking"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank", "index": "NIFTY NEXT 50", "sector": "Banking"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank", "index": "NIFTY NEXT 50", "sector": "Banking"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank", "index": "NIFTY NEXT 50", "sector": "Banking"},
    {"symbol": "CHOLAFIN.NS", "name": "Cholamandalam Investment", "index": "NIFTY NEXT 50", "sector": "Finance"},
    {"symbol": "BAJAJHLDNG.NS", "name": "Bajaj Holdings", "index": "NIFTY NEXT 50", "sector": "Finance"},
    {"symbol": "RECLTD.NS", "name": "REC Limited", "index": "NIFTY NEXT 50", "sector": "Finance"},
    {"symbol": "PFC.NS", "name": "Power Finance Corporation", "index": "NIFTY NEXT 50", "sector": "Finance"},
    {"symbol": "IRFC.NS", "name": "Indian Railway Finance Corp", "index": "NIFTY NEXT 50", "sector": "Finance"},
    {"symbol": "MOTHERSON.NS", "name": "Samvardhana Motherson", "index": "NIFTY NEXT 50", "sector": "Auto Ancillary"},
    {"symbol": "BOSCHLTD.NS", "name": "Bosch India", "index": "NIFTY NEXT 50", "sector": "Auto Ancillary"},
    {"symbol": "MFSL.NS", "name": "Max Financial Services", "index": "NIFTY NEXT 50", "sector": "Insurance"},
    {"symbol": "ICICIlombard.NS", "name": "ICICI Lombard", "index": "NIFTY NEXT 50", "sector": "Insurance"},
    {"symbol": "ICICIGI.NS", "name": "ICICI Lombard GIC", "index": "NIFTY NEXT 50", "sector": "Insurance"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma", "index": "NIFTY NEXT 50", "sector": "Pharma"},

    # NIFTY MIDCAP
    {"symbol": "DIXON.NS", "name": "Dixon Technologies", "index": "NIFTY MIDCAP", "sector": "Electronics"},
    {"symbol": "KALYANKJIL.NS", "name": "Kalyan Jewellers", "index": "NIFTY MIDCAP", "sector": "Jewellery"},
    {"symbol": "TRENT.NS", "name": "Trent (Westside)", "index": "NIFTY MIDCAP", "sector": "Retail"},
    {"symbol": "VOLTAS.NS", "name": "Voltas", "index": "NIFTY MIDCAP", "sector": "Electricals"},
    {"symbol": "CROMPTON.NS", "name": "Crompton Greaves Consumer", "index": "NIFTY MIDCAP", "sector": "Electricals"},
    {"symbol": "POLYCAB.NS", "name": "Polycab India", "index": "NIFTY MIDCAP", "sector": "Electricals"},
    {"symbol": "ASTRAL.NS", "name": "Astral Limited", "index": "NIFTY MIDCAP", "sector": "Pipes"},
    {"symbol": "SUPREMEIND.NS", "name": "Supreme Industries", "index": "NIFTY MIDCAP", "sector": "Pipes"},
    {"symbol": "PAGEIND.NS", "name": "Page Industries (Jockey)", "index": "NIFTY MIDCAP", "sector": "Apparel"},
    {"symbol": "MCDOWELL-N.NS", "name": "United Spirits", "index": "NIFTY MIDCAP", "sector": "Beverages"},
    {"symbol": "UNITEDBRW.NS", "name": "United Breweries", "index": "NIFTY MIDCAP", "sector": "Beverages"},
    {"symbol": "RADICO.NS", "name": "Radico Khaitan", "index": "NIFTY MIDCAP", "sector": "Beverages"},
    {"symbol": "ABCAPITAL.NS", "name": "Aditya Birla Capital", "index": "NIFTY MIDCAP", "sector": "Finance"},
    {"symbol": "L&TFH.NS", "name": "L&T Finance Holdings", "index": "NIFTY MIDCAP", "sector": "Finance"},
    {"symbol": "SUNDARMFIN.NS", "name": "Sundaram Finance", "index": "NIFTY MIDCAP", "sector": "Finance"},
    {"symbol": "MANAPPURAM.NS", "name": "Manappuram Finance", "index": "NIFTY MIDCAP", "sector": "Finance"},
    {"symbol": "LICHSGFIN.NS", "name": "LIC Housing Finance", "index": "NIFTY MIDCAP", "sector": "Finance"},
    {"symbol": "BHEL.NS", "name": "Bharat Heavy Electricals", "index": "NIFTY MIDCAP", "sector": "Engineering"},
    {"symbol": "BEL.NS", "name": "Bharat Electronics", "index": "NIFTY MIDCAP", "sector": "Defence"},
    {"symbol": "HAL.NS", "name": "Hindustan Aeronautics", "index": "NIFTY MIDCAP", "sector": "Defence"},
    {"symbol": "COCHINSHIP.NS", "name": "Cochin Shipyard", "index": "NIFTY MIDCAP", "sector": "Defence"},
    {"symbol": "MAZAGON.NS", "name": "Mazagon Dock Shipbuilders", "index": "NIFTY MIDCAP", "sector": "Defence"},
    {"symbol": "GRINDWELL.NS", "name": "Grindwell Norton", "index": "NIFTY MIDCAP", "sector": "Abrasives"},
    {"symbol": "CUMMINSIND.NS", "name": "Cummins India", "index": "NIFTY MIDCAP", "sector": "Engineering"},
    {"symbol": "THERMAX.NS", "name": "Thermax", "index": "NIFTY MIDCAP", "sector": "Engineering"},
    {"symbol": "ABB.NS", "name": "ABB India", "index": "NIFTY MIDCAP", "sector": "Engineering"},
    {"symbol": "SCHAEFFLER.NS", "name": "Schaeffler India", "index": "NIFTY MIDCAP", "sector": "Auto Ancillary"},
    {"symbol": "SUNDRMFAST.NS", "name": "Sundram Fasteners", "index": "NIFTY MIDCAP", "sector": "Auto Ancillary"},
    {"symbol": "APOLLOTYRE.NS", "name": "Apollo Tyres", "index": "NIFTY MIDCAP", "sector": "Auto Ancillary"},
    {"symbol": "MRF.NS", "name": "MRF", "index": "NIFTY MIDCAP", "sector": "Tyres"},
    {"symbol": "CEAT.NS", "name": "CEAT", "index": "NIFTY MIDCAP", "sector": "Tyres"},
    {"symbol": "BALKRISIND.NS", "name": "Balkrishna Industries", "index": "NIFTY MIDCAP", "sector": "Tyres"},
    {"symbol": "TVSMOTOR.NS", "name": "TVS Motor Company", "index": "NIFTY MIDCAP", "sector": "Auto"},
    {"symbol": "ASHOKLEY.NS", "name": "Ashok Leyland", "index": "NIFTY MIDCAP", "sector": "Auto"},
    {"symbol": "FORCEMOT.NS", "name": "Force Motors", "index": "NIFTY MIDCAP", "sector": "Auto"},
    {"symbol": "ESCORTS.NS", "name": "Escorts Kubota", "index": "NIFTY MIDCAP", "sector": "Auto"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoi Realty", "index": "NIFTY MIDCAP", "sector": "Real Estate"},
    {"symbol": "GODREJPROP.NS", "name": "Godrej Properties", "index": "NIFTY MIDCAP", "sector": "Real Estate"},
    {"symbol": "PRESTIGE.NS", "name": "Prestige Estates", "index": "NIFTY MIDCAP", "sector": "Real Estate"},
    {"symbol": "PHOENIXLTD.NS", "name": "Phoenix Mills", "index": "NIFTY MIDCAP", "sector": "Real Estate"},
    {"symbol": "DLF.NS", "name": "DLF Limited", "index": "NIFTY MIDCAP", "sector": "Real Estate"},
    {"symbol": "LODHA.NS", "name": "Macrotech Developers (Lodha)", "index": "NIFTY MIDCAP", "sector": "Real Estate"},
    {"symbol": "IPCALAB.NS", "name": "IPCA Laboratories", "index": "NIFTY MIDCAP", "sector": "Pharma"},
    {"symbol": "ALKEM.NS", "name": "Alkem Laboratories", "index": "NIFTY MIDCAP", "sector": "Pharma"},
    {"symbol": "LALPATHLAB.NS", "name": "Dr Lal PathLabs", "index": "NIFTY MIDCAP", "sector": "Healthcare"},
    {"symbol": "METROPOLIS.NS", "name": "Metropolis Healthcare", "index": "NIFTY MIDCAP", "sector": "Healthcare"},
    {"symbol": "MAXHEALTH.NS", "name": "Max Healthcare", "index": "NIFTY MIDCAP", "sector": "Healthcare"},
    {"symbol": "FORTIS.NS", "name": "Fortis Healthcare", "index": "NIFTY MIDCAP", "sector": "Healthcare"},
    {"symbol": "CONCOR.NS", "name": "Container Corporation", "index": "NIFTY MIDCAP", "sector": "Logistics"},
    {"symbol": "DELHIVERY.NS", "name": "Delhivery", "index": "NIFTY MIDCAP", "sector": "Logistics"},
    {"symbol": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences", "index": "NIFTY MIDCAP", "sector": "Pharma"},

    # INDICES
    {"symbol": "^NSEI", "name": "NIFTY 50 Index", "index": "INDEX", "sector": "Index"},
    {"symbol": "^NSEBANK", "name": "NIFTY Bank Index", "index": "INDEX", "sector": "Index"},
    {"symbol": "^BSESN", "name": "BSE SENSEX", "index": "INDEX", "sector": "Index"},
    {"symbol": "^CNXIT", "name": "NIFTY IT Index", "index": "INDEX", "sector": "Index"},
    {"symbol": "^CNXAUTO", "name": "NIFTY Auto Index", "index": "INDEX", "sector": "Index"},
    {"symbol": "^CNXPHARMA", "name": "NIFTY Pharma Index", "index": "INDEX", "sector": "Index"},
]